(function(window,document){"use strict";
var KEY="pacificEducationLegalFrameworkV1";
var state={version:1,status:"Configured by authorised institution or authority",source:"",authority:"",effectiveDate:"",reviewDate:"",legalLanguage:"English"};
function esc(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c];});}
function getState(){return JSON.parse(JSON.stringify(state));}
function load(){try{var x=localStorage.getItem(KEY);if(x){var v=JSON.parse(x);if(v&&typeof v==="object")state=Object.assign({},state,v);}}catch(_){}try{if(window.PacificEducationCountryConfig&&window.PacificEducationCountryConfig.getState){var c=window.PacificEducationCountryConfig.getState();state.legalLanguage=c.legalLanguage||c.language||state.legalLanguage;}}catch(_){}render();return getState();}
function render(){var app=document.getElementById("app");if(!app)return;var s=document.getElementById("pacificEducationLegalLanguageMain");if(!s){s=document.createElement("section");s.id="pacificEducationLegalLanguageMain";s.setAttribute("aria-label","Country language and legal framework");var n=document.getElementById("userFirstNavigation");if(n&&n.parentNode)n.parentNode.insertBefore(s,n.nextSibling);else app.insertBefore(s,app.firstChild);}
var c=window.PacificEducationCountryConfig&&window.PacificEducationCountryConfig.getState?window.PacificEducationCountryConfig.getState():{country:"Configured country",language:"English",educationAuthority:"Authorised education authority"};state.legalLanguage=c.legalLanguage||c.language||state.legalLanguage;
s.innerHTML="<h2>Country, Language & Legal Framework</h2><p><strong>Country / Region:</strong> "+esc(c.country)+"</p><p><strong>Main platform language:</strong> "+esc(c.language)+"</p><p><strong>Legal / regulatory language:</strong> "+esc(state.legalLanguage)+"</p><p><strong>Education authority:</strong> "+esc(c.educationAuthority)+"</p><p><strong>Framework status:</strong> "+esc(state.status)+"</p><p><small>Authoritative legal or regulatory wording must come from the authorised source. Pacedu summaries or translations do not replace the authoritative text.</small></p><details><summary>View framework information</summary><p><strong>Authority/source:</strong> "+esc(state.authority||"Not recorded")+"</p><p><strong>Source reference:</strong> "+esc(state.source||"Not recorded")+"</p><p><strong>Effective date:</strong> "+esc(state.effectiveDate||"Not recorded")+"</p><p><strong>Review date:</strong> "+esc(state.reviewDate||"Not recorded")+"</p></details>";}
function configure(v,authorized){if(!authorized||!v||typeof v!=="object")return {ok:false,error:"Authorised configuration required."};state=Object.assign({},state,v,{version:1});try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){}render();return {ok:true,state:getState()};}
document.addEventListener("pacificEducationCountryConfigChanged",function(e){if(e&&e.detail){state.legalLanguage=e.detail.legalLanguage||e.detail.language||state.legalLanguage;}render();});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",load);else load();
window.PacificEducationLegalFramework={load:load,getState:getState,render:render,configure:configure};
})(window,document);