/* =========================================================
 * PACIFIC EDUCATION — ACHIEVEMENT INDICATOR ACTIVITY MAPPER
 * ========================================================= */
(function(window){"use strict";
var VERSION="1.1.0";
var ACTIVITY_TYPES=Object.freeze(["teach","guided-practice","independent-practice","application","check-assessment","remedial-extension"]);
function copy(v){return JSON.parse(JSON.stringify(v));}
function registry(){return window.PacificEducationCurriculumAlignmentRegistry;}
function classContext(){var r=window.PacificEducationTeacherClassRosterContext;if(!r||typeof r.getClassId!=="function"||typeof r.getClass!=="function")return null;var id=String(r.getClassId()||"").trim();if(!id)return null;var c=r.getClass(id);return c?{classId:id,level:String(c.level||"").trim()}:null;}
function verifiedIndicators(filters){var r=registry(),f=filters||{},ctx=classContext();if(!r||typeof r.list!=="function"||!ctx)return [];f.classId=ctx.classId;f.level=f.level||ctx.level;return r.list(f).filter(function(x){return x.status==="VALIDATED"||x.validationStatus==="VALIDATED"||x.indicatorStatus==="VALIDATED"||x.status==="SOURCE_VERIFIED"||x.validationStatus==="SOURCE_VERIFIED";});}
function makeActivities(indicator){var id=String(indicator.id||indicator.indicatorId||indicator.rowId||"indicator"),text=String(indicator.indicatorText||indicator.achievementIndicator||"");if(!text)return [];var labels={"teach":"Teach and model the achievement indicator","guided-practice":"Guided practice with prompts and feedback","independent-practice":"Independent practice demonstrating the indicator","application":"Application: transfer the indicator to a familiar context","check-assessment":"Check assessment: collect evidence of the indicator","remedial-extension":"Remedial / extension: reteach gaps or extend mastery"};return ACTIVITY_TYPES.map(function(type,index){return{activityId:id+"-ACT-"+String(index+1).padStart(2,"0"),indicatorId:id,classId:indicator.classId||null,activityType:type,title:labels[type],taskFocus:labels[type],achievementIndicator:text,strand:indicator.strand||"",subStrand:indicator.subStrand||"",concept:indicator.subStrand||"",activitySequence:index+1,sourceDocument:indicator.sourceDocument||"",sourceLocation:indicator.sourceLocation||"",level:indicator.level||"",subjectId:indicator.subjectId||indicator.subject||"",term:indicator.term||"",status:"mapped-from-verified-indicator",prototype:true,productionEligible:false};});}
function mapIndicator(indicator){var ctx=classContext();if(!ctx)return{success:false,activities:[],reason:"Class Reference required"};if(!indicator)return{success:false,activities:[],reason:"indicator-required"};if(indicator.classId&&String(indicator.classId)!==ctx.classId)return{success:false,activities:[],reason:"Class Reference mismatch"};if(ctx.level&&indicator.level&&indicator.level!==ctx.level)return{success:false,activities:[],reason:"Class level mismatch"};if(!(indicator.status==="VALIDATED"||indicator.validationStatus==="VALIDATED"||indicator.indicatorStatus==="VALIDATED"||indicator.status==="SOURCE_VERIFIED"||indicator.validationStatus==="SOURCE_VERIFIED"))return{success:false,activities:[],reason:"indicator-not-verified"};return{success:true,indicatorId:indicator.id||indicator.indicatorId||indicator.rowId,activities:makeActivities(indicator)};}
function mapAll(filters){var indicators=verifiedIndicators(filters),activities=[];indicators.forEach(function(i){activities=activities.concat(makeActivities(i));});return{success:true,prototype:true,classId:classContext()?classContext().classId:null,verifiedIndicatorCount:indicators.length,mappedActivityCount:activities.length,activityTypes:ACTIVITY_TYPES.slice(),activities:activities};}
function coverage(filters){var indicators=verifiedIndicators(filters);return indicators.map(function(i){var mapped=makeActivities(i);return{indicatorId:i.id||i.indicatorId||i.rowId,classId:i.classId||null,level:i.level||"",subjectId:i.subjectId||i.subject||"",term:i.term||"",achievementIndicator:i.indicatorText||i.achievementIndicator,activityCount:mapped.length,fullyMapped:mapped.length===ACTIVITY_TYPES.length};});}
window.PacificEducationAchievementIndicatorActivityMapper=Object.freeze({name:"PacificEducationAchievementIndicatorActivityMapper",version:VERSION,activityTypes:ACTIVITY_TYPES,verifiedIndicators:verifiedIndicators,mapIndicator:mapIndicator,mapAll:mapAll,coverage:coverage});
})(window);
