/* Pacific Education — School Transfer Intake */
(function(window,document){
 "use strict"; var VERSION="1.0.0",KEY="pacificEducationSchoolTransfers";
 function read(){try{return JSON.parse(localStorage.getItem(KEY)||"[]");}catch(e){return [];}}
 function save(a){localStorage.setItem(KEY,JSON.stringify(a.slice(-500)));}
 function start(){
  var target=document.getElementById("pacificEducationTransferIntake");if(!target)return false;
  target.innerHTML='<h3>School Transfer / New School Intake</h3><p>For learners transferring during the school year. Existing verified learning evidence can travel with the learner; the receiving school confirms placement.</p><label>Previous school <input id="peTransferFrom"></label><br><label>Receiving school <input id="peTransferTo"></label><br><label>Current class <select id="peTransferClass"><option>Class 1</option><option>Class 2</option><option>Class 3</option><option>Class 4</option><option>Class 5</option><option>Class 6</option><option>Class 7</option><option>Class 8</option><option>Class 9</option><option>Class 10</option><option>Class 11</option><option>Class 12</option><option>Class 13</option></select></label><br><label>Transfer date <input id="peTransferDate" type="date"></label><br><label>Verified learner reference <input id="peTransferStudent"></label><br><button type="button" id="peTransferSave">Create transfer intake record</button><div id="peTransferStatus" aria-live="polite"></div>';
  document.getElementById("peTransferSave").onclick=function(){var from=document.getElementById("peTransferFrom").value.trim(),to=document.getElementById("peTransferTo").value.trim(),sid=document.getElementById("peTransferStudent").value.trim();if(!from||!to||!sid){document.getElementById("peTransferStatus").textContent="Previous school, receiving school and learner reference are required.";return;}var r={transferId:"transfer-"+Date.now(),studentId:sid,previousSchool:from,receivingSchool:to,classLevel:document.getElementById("peTransferClass").value,transferDate:document.getElementById("peTransferDate").value||new Date().toISOString().slice(0,10),status:"pending-receiving-school-confirmation",createdAt:new Date().toISOString(),preserveProgress:true,requireBaselineOnArrival:true,prototype:true};var a=read();a.push(r);save(a);localStorage.setItem("pacificEducationTransferContext",JSON.stringify(r));document.getElementById("peTransferStatus").textContent="Transfer intake created. Receiving-school confirmation is required; prior evidence is not overwritten.";document.dispatchEvent(new CustomEvent("pacificEducationSchoolTransferCreated",{detail:r}));};
 }
 function current(){try{return JSON.parse(localStorage.getItem("pacificEducationTransferContext")||"null");}catch(e){return null;}}
 window.PacificEducationSchoolTransfer=Object.freeze({version:VERSION,start:start,current:current,list:read});
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){var t=document.getElementById("pacificEducationTransferIntake");if(t)t.innerHTML='<p>Transfer learners can carry verified learning evidence to the receiving school while completing receiving-school confirmation and a new baseline check.</p><button type="button" id="peOpenTransfer">Open transfer intake</button>';var b=document.getElementById("peOpenTransfer");if(b)b.onclick=start;});
})(window,document);