(function(window){"use strict";
var VERSION="1.0.0";
function reg(){return window.PacificEducationCurriculumAlignmentRegistry}
function calendar(){return window.PacificEducationTeacherCalendar}
function integration(){return window.PacificEducationCurriculumIntegrationEngine}
function copy(v){return JSON.parse(JSON.stringify(v));}
function generateDailyPlan(c){c=c||{};var r=reg();if(!r)return{success:false,error:"Alignment Registry unavailable"};var items=r.list({level:c.level,subjectId:c.subjectId,term:c.term}).filter(function(x){return x.status!=="retired"});if(c.maximumIndicators)items=items.slice(0,c.maximumIndicators);var cal=calendar()?calendar().getDayByNumber(c.dayNumber||1):{type:"learning"};var out={success:true,status:cal.type==="revision"?"revision-plan":cal.type==="exam"?"exam-day":"learning-day",dayNumber:Number(c.dayNumber||1),level:c.level||null,subjectId:c.subjectId||null,term:c.term||null,calendar:cal,indicators:items.map(function(i){return{indicator:copy(i),activities:[{id:i.id+"-A1",title:"Daily practice for "+i.strand,instructions:i.indicatorText}],integration:integration()?integration().buildFromIndicator(i,c.level,c.subjectId):null,assessments:[]};}),activities:[],assessments:[],integrationModel:{coreShare:0.5,integratedShare:0.5},prototype:true};out.indicators.forEach(function(i){out.activities=out.activities.concat(i.activities)});return out;}
function generateProgrammePlan(c){c=c||{};var days=[];for(var d=Number(c.startDay||1);d<=Number(c.endDay||c.startDay||1);d++){var x=copy(c);x.dayNumber=d;days.push(generateDailyPlan(x));}return{success:true,days:days,prototype:true};}
function validate(){return{valid:Boolean(reg()),prototype:true};}
window.PacificEducationDailyCurriculumEngine=Object.freeze({name:"PacificEducationDailyCurriculumEngine",version:VERSION,generateDailyPlan:generateDailyPlan,generateProgrammePlan:generateProgrammePlan,validate:validate,reset:function(){}});})(window);