/* Pacific Education — breathing blue focus guide.
 * Additive accessibility/navigation aid. Shows exactly where to enter/select
 * the current step with a calm blue breathing ring. Preserves #856 voice.
 */
(function(window,document){
"use strict";
var STYLE_ID="pacificEducationBreathingFocusStyle",FOCUS_CLASS="pacific-breathing-focus",LABEL_CLASS="pacific-breathing-focus-label",LOCK_CLASS="pacific-breathing-locked",READY_CLASS="pacific-next-breathing-ready",lastTarget=null,observer=null,busy=false;
function injectStyle(){if(document.getElementById(STYLE_ID))return;var s=document.createElement("style");s.id=STYLE_ID;s.textContent=".pacific-breathing-focus{position:relative!important;border:3px solid #1597ff!important;box-shadow:0 0 0 3px rgba(21,151,255,.18),0 0 18px rgba(21,151,255,.55)!important;animation:paceduBlueBreathe 1.8s ease-in-out infinite!important;z-index:4!important}.pacific-breathing-focus-label{display:block;margin:0 0 8px;padding:8px 12px;border-radius:10px;background:#e7f5ff;color:#064b78;font-weight:800;border:2px solid #1597ff}.pacific-breathing-locked{opacity:.55!important;cursor:not-allowed!important}.pacific-next-breathing-ready{animation:paceduGreenBreathe 1.8s ease-in-out infinite!important;transform:translateZ(0)}@keyframes paceduBlueBreathe{0%,100%{box-shadow:0 0 0 3px rgba(21,151,255,.16),0 0 12px rgba(21,151,255,.35)}50%{box-shadow:0 0 0 7px rgba(21,151,255,.28),0 0 26px rgba(21,151,255,.72)}}@keyframes paceduGreenBreathe{0%,100%{box-shadow:0 0 0 2px rgba(22,138,58,.18),0 0 8px rgba(22,138,58,.25)}50%{box-shadow:0 0 0 7px rgba(22,138,58,.32),0 0 24px rgba(22,138,58,.65)}}@media (prefers-reduced-motion:reduce){.pacific-breathing-focus,.pacific-next-breathing-ready{animation:none!important}}";document.head.appendChild(s)}
function clear(){if(lastTarget){lastTarget.classList.remove(FOCUS_CLASS);lastTarget.removeAttribute("data-pe-breathing-active")}Array.prototype.forEach.call(document.querySelectorAll("."+LABEL_CLASS),function(x){x.remove()});Array.prototype.forEach.call(document.querySelectorAll("."+READY_CLASS),function(x){x.classList.remove(READY_CLASS)});unlockAll();lastTarget=null}
function controls(root){return root?root.querySelectorAll("input,select,textarea,button,[role=\"button\"]"):document.querySelectorAll("input,select,textarea,button,[role=\"button\"]")}
function unlockAll(){Array.prototype.forEach.call(document.querySelectorAll("."+LOCK_CLASS),function(el){el.classList.remove(LOCK_CLASS);el.removeAttribute("aria-disabled");if(el.getAttribute("data-pe-breathing-disabled")==="1"){el.removeAttribute("disabled");el.removeAttribute("data-pe-breathing-disabled")}})}
function lockTo(target,root){var list=controls(root);Array.prototype.forEach.call(list,function(el){var label=(el.getAttribute("aria-label")||el.textContent||"").replace(/\\s+/g," ").trim().toLowerCase();if(el===target||el.closest("."+LABEL_CLASS)||el.id==="pacificEducationStopSpeechButton"||el.id==="pacificEducationWelcomeVoiceButton"||el.id==="pacificEducationAIPlaybackButton"||/\\b(back|next|stop|hear instructions|ai playback)\\b/.test(label)||el.hasAttribute("data-audio-command-for"))return;if(el.disabled)return;el.setAttribute("disabled","disabled");el.setAttribute("data-pe-breathing-disabled","1");el.classList.add(LOCK_CLASS);el.setAttribute("aria-disabled","true")})}
function readyNext(root){var n=root&&root.querySelector("#welcomeNextButton,#paceduVisionNext,#paceduRulesContinue,#registrationNextButton,#prototypeNextButton,#levelNextButton,#subjectNextButton,#termNextButton,#capabilityNextButton,#dailyNextButton,#practiceNextButton,#assessmentNextButton,#peSequentialNext");if(!n)n=document.querySelector("#welcomeNextButton,#paceduVisionNext,#paceduRulesContinue,#registrationNextButton,#prototypeNextButton,#levelNextButton,#subjectNextButton,#termNextButton,#capabilityNextButton,#dailyNextButton,#practiceNextButton,#assessmentNextButton,#peSequentialNext");if(n&&!n.disabled)n.classList.add(READY_CLASS)}
function focus(target,text){if(!target||target.disabled||target.hidden)return false;clear();var root=target.closest("#pacificEducationIdentityRegistration,#pacificEducationPilotPages,#pacificEducationSequentialRoleWorkspace")||target.parentElement;lockTo(target,root);var box=target.closest(".pe-user-box,#pacificEducationRegistrationBox,.pacedu-entry-card,.pacedu-entry-grid section,.pacedu-agreement")||target;var p=document.createElement("div");p.className=LABEL_CLASS;p.setAttribute("role","status");p.setAttribute("aria-live","polite");p.textContent=text;target.parentNode.insertBefore(p,target);box.classList.add(FOCUS_CLASS);box.setAttribute("data-pe-breathing-active","true");lastTarget=box;try{box.scrollIntoView({behavior:"smooth",block:"center"})}catch(e){}return true}
function visible(el){if(!el||el.hidden)return false;var s=window.getComputedStyle(el);return s.display!=="none"&&s.visibility!=="hidden"}
function choose(){var reg=document.getElementById("pacificEducationIdentityRegistration");if(visible(reg)&&!document.getElementById("pacificEducationSequentialRoleWorkspace")){var role=document.querySelector("#pilotUserRoleCards .pe-user-role-card[aria-pressed='true']"),name=document.getElementById("pilotRegistrationName"),country=document.getElementById("pacificEducationCountrySelect"),language=document.getElementById("pacificEducationLanguageSelect"),open=document.getElementById("userRegistrationOpenButton"),first=document.querySelector("#pilotUserRoleCards .pe-user-role-card");if(visible(country)&&!country.value)return focus(country,"STEP 1 — Select your country here.");if(visible(country)&&country.value&&visible(language)&&!language.value)return focus(language,"STEP 2 — Correct. Country accepted. Now select your language here.");if(visible(language)&&language.value&&visible(open))return focus(open,"STEP 3 — Correct. Language accepted. Open User Registration here.");if(visible(document.getElementById("pilotUserRoleCards"))&&!role&&first)return focus(first,"STEP 4 — Correct. Registration opened. Choose your user role here.");if(visible(document.getElementById("pilotUserRoleCards"))&&role&&visible(name)&&!String(name.value||"").trim())return focus(name,"STEP 5 — Correct. Role accepted. Enter your display name here.");if(visible(name)&&String(name.value||"").trim()){var save=document.getElementById("pilotRegistrationSaveButton");if(visible(save)&&!save.disabled)return focus(save,"STEP 6 — Details accepted. Save Registration to continue.");} }
var gateway=document.querySelector("body.pacedu-entry-mode .pacedu-entry-page");if(gateway&&visible(gateway)){var gcontrols=gateway.querySelectorAll("input:not([disabled]),select:not([disabled]),textarea:not([disabled])");for(var g=0;g<gcontrols.length;g++)if(visible(gcontrols[g])&&!String(gcontrols[g].value||"").trim())return focus(gcontrols[g],"CURRENT STEP — Complete this box first.");var gnext=gateway.querySelector("#paceduVisionNext,#paceduRulesContinue,#welcomeNextButton");if(gnext&&!gnext.disabled){unlockAll();readyNext(gateway);return false;}}
var shell=document.getElementById("pacificEducationSequentialRoleWorkspace");if(visible(shell)){var page=document.getElementById("peSequentialPage");if(page){var i=page.querySelector("input:not([disabled]),select:not([disabled]),textarea:not([disabled]),button:not([disabled])");if(i)return focus(i,i.tagName==="BUTTON"?"CURRENT STEP — Use this control to complete the step.":"CURRENT STEP — Enter or select your information here.")}}
var candidates=document.querySelectorAll("body.pacedu-entry-mode .pacedu-entry-page input:not([disabled]),body.pacedu-entry-mode .pacedu-entry-page select:not([disabled]),body.pacedu-entry-mode .pacedu-entry-page textarea:not([disabled])");for(var j=0;j<candidates.length;j++){if(visible(candidates[j])&&String(candidates[j].type||"").toLowerCase()!=="hidden"&&String(candidates[j].type||"").toLowerCase()!=="checkbox")return focus(candidates[j],"CURRENT PAGE — Complete this user box, then use the green Next button.");}var activePage=document.querySelector("body.pacedu-entry-mode .pacedu-entry-page");if(activePage&&visible(activePage)){var next=activePage.querySelector("#paceduVisionNext,#paceduRulesContinue,#welcomeNextButton");if(next&&!next.disabled){unlockAll();readyNext(activePage);return false;}}return false}
function refresh(){if(busy)return;busy=true;try{injectStyle();choose()}finally{busy=false}}
function init(){injectStyle();if(observer)return;observer=new MutationObserver(function(){clearTimeout(init._t);init._t=setTimeout(refresh,80)});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["hidden","style","aria-pressed","value"]});setTimeout(refresh,250);setInterval(refresh,1200)}
window.PacificEducationBreathingFocusGuide={version:"1.0.1",refresh:refresh,clear:clear};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})(window,document);
