(function(window){"use strict";
var VERSION="1.0.0",records=[];
function copy(v){return JSON.parse(JSON.stringify(v));}
function source(id,title,status){return {id:id,title:title,status:status||"unverified",authority:null,document:null,verifiedBy:null,verifiedDate:null};}
function add(r){var x=copy(r);records.push(x);return x;}
add({id:"C1-ENG-P-001",level:"Class 1",subjectId:"English",term:"Term 1",strand:"Reading",indicatorText:"Read a short age-appropriate passage and identify the main idea.",learningOutcome:"Learner demonstrates understanding of a short passage.",integrationSubjects:["Science","Mathematics"],source:source("SRC-C1-ENG-PROT-001","Prototype planning record","unverified"),status:"prototype",coverageStatus:"not-started",productionEligible:false});
add({id:"C1-ENG-P-002",level:"Class 1",subjectId:"English",term:"Term 1",strand:"Speaking and Listening",indicatorText:"Listen to and respond to a short spoken message using appropriate words.",learningOutcome:"Learner communicates a simple response.",integrationSubjects:["Social Science","Health"],source:source("SRC-C1-ENG-PROT-002","Prototype planning record","unverified"),status:"prototype",coverageStatus:"not-started",productionEligible:false});
add({id:"C1-ENG-P-003",level:"Class 1",subjectId:"English",term:"Term 1",strand:"Vocabulary",indicatorText:"Use familiar words to describe people, objects and everyday actions.",learningOutcome:"Learner uses vocabulary in context.",integrationSubjects:["Science","Arts"],source:source("SRC-C1-ENG-PROT-003","Prototype planning record","unverified"),status:"prototype",coverageStatus:"not-started",productionEligible:false});
add({id:"C1-ENG-P-004",level:"Class 1",subjectId:"English",term:"Term 1",strand:"Writing",indicatorText:"Write simple words and sentences with appropriate spacing and basic punctuation.",learningOutcome:"Learner produces simple written English.",integrationSubjects:["Mathematics","Social Science"],source:source("SRC-C1-ENG-PROT-004","Prototype planning record","unverified"),status:"prototype",coverageStatus:"not-started",productionEligible:false});
function list(f){f=f||{};return records.filter(function(r){return(!f.level||r.level===f.level)&&(!f.subjectId||r.subjectId===f.subjectId)&&(!f.term||r.term===f.term)&&(!f.sourceStatus||r.source.status===f.sourceStatus)}).map(copy);}
function get(id){var r=records.find(function(x){return x.id===id});return r?copy(r):null;}
function registerWithRegistry(){var reg=window.PacificEducationCurriculumAlignmentRegistry;if(!reg)return{success:false,error:"Alignment Registry unavailable"};var verifier=window.PacificEducationCurriculumSourceVerification;records.forEach(function(r){reg.registerIndicator(r);if(verifier&&typeof verifier.register==="function"){verifier.register({id:r.id,level:r.level,subjectId:r.subjectId,term:r.term,indicatorText:r.indicatorText,source:r.source,verificationStatus:r.source.status==="verified"?"curriculum-verified":"unverified"});}});return{success:true,count:records.length};}
function validate(){var errors=[];records.forEach(function(r){if(!r.id||!r.level||!r.subjectId||!r.term||!r.indicatorText)errors.push(r.id||"record");if(r.source.status!=="verified"&&r.productionEligible)errors.push(r.id+": productionEligible requires verified source")});return{valid:errors.length===0,errors:errors,count:records.length};}
function markSourceVerified(id,data){var r=records.find(function(x){return x.id===id});if(!r)throw new Error("Curriculum record not found");data=data||{};if(!data.authority||!data.document||!data.verifiedBy||!data.verifiedDate)throw new Error("Authority, document, verifier and date are required");r.source.status="verified";r.source.authority=data.authority;r.source.document=data.document;r.source.verifiedBy=data.verifiedBy;r.source.verifiedDate=data.verifiedDate;return copy(r);}
function approveForProduction(id,data){var r=records.find(function(x){return x.id===id});if(!r)throw new Error("Curriculum record not found");if(r.source.status!=="verified")throw new Error("Source must be verified first");data=data||{};if(!data.approvedBy||!data.approvedDate)throw new Error("Approval identity and date are required");r.productionEligible=true;r.approvedBy=data.approvedBy;r.approvedDate=data.approvedDate;r.status="approved";return copy(r);}
window.PacificEducationCurriculumData=Object.freeze({name:"PacificEducationCurriculumData",version:VERSION,list:list,get:get,registerWithRegistry:registerWithRegistry,validate:validate,markSourceVerified:markSourceVerified,approveForProduction:approveForProduction,exportData:function(){return copy(records)}});})(window);