/* Pacific Education — breathing blue focus guide.
 * Additive accessibility/navigation aid. Shows exactly where to enter/select
 * the current step with a calm blue breathing ring. Preserves #856 voice.
 */
(function(window,document){
"use strict";
var STYLE_ID="pacificEducationBreathingFocusStyle",FOCUS_CLASS="pacific-breathing-focus",LABEL_CLASS="pacific-breathing-focus-label",lastTarget=null,observer=null,busy=false;
function injectStyle(){if(document.getElementById(STYLE_ID))return;var s=document.createElement("style");s.id=STYLE_ID;s.textContent=".pacific-breathing-focus{position:relative!important;border:3px solid #1597ff!important;box-shadow:0 0 0 3px rgba(21,151,255,.18),0 0 18px rgba(21,151,255,.55)!important;animation:paceduBlueBreathe 1.8s ease-in-out infinite!important;z-index:4!important}.pacific-breathing-focus-label{display:block;margin:0 0 8px;padding:8px 12px;border-radius:10px;background:#e7f5ff;color:#064b78;font-weight:800;border:2px solid #1597ff}@keyframes paceduBlueBreathe{0%,100%{box-shadow:0 0 0 3px rgba(21,151,255,.16),0 0 12px rgba(21,151,255,.35)}50%{box-shadow:0 0 0 7px rgba(21,151,255,.28),0 0 26px rgba(21,151,255,.72)}}@media (prefers-reduced-motion:reduce){.pacific-breathing-focus{animation:none!important}}";document.head.appendChild(s)}
function clear(){if(lastTarget){lastTarget.classList.remove(FOCUS_CLASS);lastTarget.removeAttribute("data-pe-breathing-active")}Array.prototype.forEach.call(document.querySelectorAll("."+LABEL_CLASS),function(x){x.remove()});lastTarget=null}
function focus(target,text){if(!target||target.disabled||target.hidden)return false;clear();var p=document.createElement("div");p.className=LABEL_CLASS;p.setAttribute("role","status");p.setAttribute("aria-live","polite");p.textContent=text;target.parentNode.insertBefore(p,target);target.classList.add(FOCUS_CLASS);target.setAttribute("data-pe-breathing-active","true");lastTarget=target;try{target.scrollIntoView({behavior:"smooth",block:"center"})}catch(e){}return true}
function visible(el){if(!el||el.hidden)return false;var s=window.getComputedStyle(el);return s.display!=="none"&&s.visibility!=="hidden"}
function choose(){var reg=document.getElementById("pacificEducationIdentityRegistration");if(visible(reg)&&!document.getElementById("pacificEducationSequentialRoleWorkspace")){var role=document.querySelector("#pilotUserRoleCards .pe-user-role-card[aria-pressed='true']"),name=document.getElementById("pilotRegistrationName"),country=document.getElementById("pacificEducationCountrySelect"),language=document.getElementById("pacificEducationLanguageSelect"),open=document.getElementById("userRegistrationOpenButton"),first=document.querySelector("#pilotUserRoleCards .pe-user-role-card");if(visible(country)&&!country.value)return focus(country,"STEP 1 — Select your country here.");if(visible(language)&&!language.value)return focus(language,"STEP 2 — Select your language here.");if(visible(open))return focus(open,"STEP 3 — Open User Registration here.");if(visible(document.getElementById("pilotUserRoleCards"))&&!role&&first)return focus(first,"STEP 4 — Choose your user role here.");if(visible(name)&&!String(name.value||"").trim())return focus(name,"STEP 5 — Enter your display name here.")}
var shell=document.getElementById("pacificEducationSequentialRoleWorkspace");if(visible(shell)){var page=document.getElementById("peSequentialPage");if(page){var i=page.querySelector("input:not([disabled]),select:not([disabled]),textarea:not([disabled]),button:not([disabled])");if(i)return focus(i,i.tagName==="BUTTON"?"CURRENT STEP — Use this control to complete the step.":"CURRENT STEP — Enter or select your information here.")}}
var candidates=document.querySelectorAll("body.pacedu-entry-mode .pacedu-entry-page input:not([disabled]),body.pacedu-entry-mode .pacedu-entry-page select:not([disabled]),body.pacedu-entry-mode .pacedu-entry-page textarea:not([disabled]),body.pacedu-entry-mode .pacedu-entry-page button:not([disabled])");for(var j=0;j<candidates.length;j++){if(visible(candidates[j]))return focus(candidates[j],"CURRENT PAGE — Start here, then use the green Next button.");}return false}
function refresh(){if(busy)return;busy=true;try{injectStyle();choose()}finally{busy=false}}
function init(){injectStyle();if(observer)return;observer=new MutationObserver(function(){clearTimeout(init._t);init._t=setTimeout(refresh,80)});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["hidden","style","aria-pressed","value"]});setTimeout(refresh,250);setInterval(refresh,1200)}
window.PacificEducationBreathingFocusGuide={version:"1.0.0",refresh:refresh,clear:clear};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})(window,document);
